production:
  cloud_name: dtlq78n5z
  api_key: '375783462319189'
  api_secret: 'JoIIr8wCXVBhT5pb9nrI4xX8fqA'

development:
  cloud_name: dtlq78n5z
  api_key: '375783462319189'
  api_secret: 'JoIIr8wCXVBhT5pb9nrI4xX8fqA'